#!/bin/bash


# If gcc is used to build kernel modules, the `compile_commands.json`
# file generated by `bear -- make` contains some GCC-specific options,
# which may cause `clangd` to report errors.
# This scripts modifies `compile_commands.json` to address the issue.
#
# Usage:
#	$ bear -- make
#	$ ./modify_compile_commands_json.sh
#

sed -i '/-mpreferred-stack-boundary=3/d' compile_commands.json
sed -i '/-mindirect-branch=thunk-extern/d' compile_commands.json
sed -i '/-mindirect-branch-register/d' compile_commands.json
sed -i '/-fno-allow-store-data-races/d' compile_commands.json
sed -i '/-fconserve-stack/d' compile_commands.json
sed -i '/bounds-strict/d' compile_commands.json
sed -i '/-mrecord-mcount/d' compile_commands.json
